CREATE DATABASE skrik;
CREATE TABLE skrik.users ( id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, name VARCHAR(50) NOT NULL, email VARCHAR(100) NOT NULL, phone VARCHAR(20) NOT NULL, reg_id VARCHAR(200), pass VARCHAR(100), status VARCHAR(250) NOT NULL );
CREATE TABLE skrik.msgs ( id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, userid_from BIGINT NOT NULL, userid_to BIGINT NOT NULL, message VARCHAR(250), status VARCHAR(14) NOT NULL, timestamp INT(14) );
CREATE USER 'skrik'@'localhost' IDENTIFIED BY 'skrik123';
GRANT DELETE, INSERT, SELECT, UPDATE ON * . * TO 'skrik'@'localhost';
FLUSH PRIVILEGES;
